### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by hoangnm89** [Midtrans/Midtrans-Magento2#13]
Current 2.3.0 is require:
"php": "~5.5.0|~5.6.0",

but magento 2.3.x require php 7. 
Please tag new version for current code in `master`
cc: @Xaxxis

**Comment by Xaxxis** [comment]
Hi @hoangnm89 thanks for reporting

We have already released tag new version 2.3.1 for that requirement

Regards

**Comment by hoangnm89** [comment]
thank you
