### ISSUE TITLE
Support Multishipping

### ISSUE THREAD

**Issue by ValentV1637** [Midtrans/Midtrans-Magento2#15]
Halo, saya ingin mengkonfirmasi, apakah plugin Midtrans untuk Magento ini sudah support untuk Multishipping?

Karna saya coba tidak muncul di multishipping untuk payment Midtrans.

@Xaxxis 
Terima kasih.

**Comment by Xaxxis** [comment]
Halo @ValentV1637 thank you for reaching out to us

Betul saat ini Plugins Midtrans Magento belum support untuk Multishipping ya. Kemungkinan akan tersedia pada next release, namun sayangnya kami belum mempunyai tanggal release yang tersedia.

Terima kasih

**Comment by Xaxxis** [comment]
Released on v2.5.3
