### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by ValentV1637** [Midtrans/Midtrans-Magento2#19]
per tanggal 15 Oktober 2020, untuk versi yang terbaru, saya mendapatkan response "Bad Request" ketika request token SNAP API, namun tidak terjadi pada versi 2.2.0. 

`[2020-10-15 06:30:15] MidtransLogger.ERROR: Midtrans Error (400): <html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
 | Request url: https://app.midtrans.com/snap/v1/transactions {"is_exception":false} []
`

Saya lihat perbedaannya ada pada header yang dikirim, jadi saya coba samakan dengan versi di 2.2.0.

` $curl_options = array(
        CURLOPT_URL => $url,
        CURLOPT_HTTPHEADER => array(
            'Content-Type: application/json',
            'Accept: application/json',
            'user-agent : Magento 2 Module',
            'x-plugin-name : midtrans-magento2',
            'Authorization: Basic ' . base64_encode($server_key . ':')
        ),
        CURLOPT_RETURNTRANSFER => 1,
        // CURLOPT_CAINFO => dirname(__FILE__) . "/../data/cacert.pem"
        );`

menjadi

` $curl_options = array(
        CURLOPT_URL => $url,
        CURLOPT_HTTPHEADER => array(
            'Content-Type: application/json',
            'Accept: application/json',
            'Authorization: Basic ' . base64_encode($server_key . ':')
        ),
        CURLOPT_RETURNTRANSFER => 1,
        // CURLOPT_CAINFO => dirname(__FILE__) . "/../data/cacert.pem"
        );`

pada file SnapApiRequestor.php dan ApiRequestor.php

**Comment by Xaxxis** [comment]
Hi @ValentV1637 thank you for reaching out to us

Bisa dijelasakan secara spesifik issue ini terjadi pada Magento 2 dan Plugins Midtrans versi berapa? Kareana pada saat ini, plugins kami berjalan dengan baik pada versi latest Magento 2 v2.4.0

Terima kasih

**Comment by ValentV1637** [comment]
Halo @Xaxxis ,

oh iya maaf karna tidak menyertakan version nya, versionnya bukan latest ternyata, dan yang saya gunakan adalah:
Midtrans module version: 2.3.1
Magento version: 2.3.4

issue nya adalah, snap tidak muncul, karna mendapat response "Bad Request" ketika request token.

**Comment by Xaxxis** [comment]
Hi @ValentV1637 kami sangat merekomendasikan untuk menggunakan plugins/module Midtrans Magento2 latest version ya yaitu v.2.3.3, pastikan kembali setelah upgrade module ke latest version. Melakukan flush cache storage serta compile DI. Anda dapat menggunakan command berikut dibawah ini untuk melakukan flush cache storage dan compile dependency injection dengan menjalankan pada terminal server pada lokasi root folder Magento2 anda.

```
bin/magento cache:flush
bin/magento setup:di:compile
```

Terima kasih
