### ISSUE TITLE
Custom Snap

### ISSUE THREAD

**Issue by badriyah0993** [Midtrans/Midtrans-Magento2#20]
Halo.. saya ingin menanyakan fitur. apakah bisa dengan snap ini menambahkan biaya layanan dengan perhitungan sesuai credit card yang digunakan dan installment term yg dipilih oleh customer? jika bisa bagaimana caranya. jika tidak bisa workaround nya seperti apa ya.

**Comment by Xaxxis** [comment]
Hi @badriyah0993 thank you for reaching out to us. 

Secara default plugin CMS Midtrans tidak handle biaya layanan sesuai dengan payment method yang digunakan, jika anda ingin melakukan customisasi bisa melakukan pada class [AbstractAction](https://github.com/Midtrans/Midtrans-Magento2/blob/master/Controller/Payment/AbstractAction.php#L312-L385) namun kami tidak merekomendasikannya.

Untuk cara simplenya bisa dengan melakukan penyesuaian harga peritem sesuai dengan persentase yang anda inginkan.

Terima kasih
