### ISSUE TITLE
Expired not working

### ISSUE THREAD

**Issue by ValentV1637** [Midtrans/Midtrans-Magento2#21]
Halo, saya coba set expired di config, namun di payload tidak terkirim. Saya lihat di AbstractAction seperti ini:

` if (!empty($customExpiry)) {
            $customExpiry = explode(" ", $customExpiry);
            $expiry_unit = $customExpiry[1];
            $expiry_duration = (int)$customExpiry[0];

            $payloads['expiry'] = [
                'unit' => $expiry_unit,
                'duration' => (int)$expiry_duration
            ];
        }`

$customExpiry tidak merujuk ke variable apa pun, apakah mungkin maksudnya merujuk ke config?

**Comment by Xaxxis** [comment]
Hi @ValentV1637 thank you for reaching out to us

Betul variable tersebut harusnya merujuk ke value config, untuk workaroundnya bisa merubah [line berikut](https://github.com/Midtrans/Midtrans-Magento2/blob/master/Controller/Payment/AbstractAction.php#L484-L493) menjadi seperti ini.
```
if (isset($config['custom_expiry'])) {
            $customExpiry = explode(" ", $config['custom_expiry']);
            $expiry_unit = $customExpiry[1];
            $expiry_duration = (int)$customExpiry[0];

            $payloads['expiry'] = [
                'unit' => $expiry_unit,
                'duration' => (int)$expiry_duration
            ];
        }
```
Untuk official fix nya akan inculde pada next release. Thank you
