### ISSUE TITLE
Save Credit Card 

### ISSUE THREAD

**Issue by badriyah0993** [Midtrans/Midtrans-Magento2#22]
Selamat Sore, mau tanya. kalo save credit card number di plugin midtrans untuk magento sudah bisa dipakai kah?

**Comment by Xaxxis** [comment]
Hi @badriyah0993 untuk feature save-card pada Extension/Plugins Midtrans Magento2 berjalan normal. Namun pastikan kembali untuk penggunaan feature save-card pada production, anda membutuhkan acquiring khusus. Untuk pertanyaan general lebih lanjut bisa menghubungi tim kami via email support@midtrans.com 

Terima kasih

**Comment by badriyah0993** [comment]
Baik, akan saya coba. terima kasih.

Best Regards,
Badriyah
Backend Developer (089619572775)
