### ISSUE TITLE
Checkout total double amount 

### ISSUE THREAD

**Issue by ishaqdahot** [Midtrans/Midtrans-Magento2#25]
I am using this extension on Magento 2.4 and it is working perfectly for simple products, but on configurable products, it shows the double price as of actual cart total.

**Comment by Xaxxis** [comment]
Hi, @ishaqdahot Thank you for reaching out to us. This is very dependent on your item configuration. Our extension gets the gross_amount based on the total of Magento's final item price. Could you make this more clear e.g share the screenshot of the payment page and checkout page?

For other general question, you can reach out to us via email support@midtrans.com

Thank you

**Comment by Xaxxis** [comment]
Try to reproduce this issue with Magento sample data, looks normal from our side. If you have any question may you can reach out to us via email support@midtrans.com

Thank you
