### ISSUE TITLE
Notice: Trying to get property 'status_code' of non-object

### ISSUE THREAD

**Issue by a88y** [Midtrans/Midtrans-Magento2#6]
Hallo, coba install modul midtrans di m2, tepatnya 2.3.2
Transaksi jalan normal, tapi tidak bisa terima balikan notifikasi pembayaran,

`{"0":"Notice: Trying to get property 'status_code' of non-object in \/var\/www\/html\/lib\/internal\/midtrans-php\/Midtrans\/ApiRequestor.php on line 102","1":"<pre>#1 Midtrans\\ApiRequestor::remoteCall('https:\/\/api.sand...', 'SB-Mid-server-4P...', false, false) called at [lib\/internal\/midtrans-php\/Midtrans\/ApiRequestor.php:22]\n#2 Midtrans\\ApiRequestor::get('https:\/\/api.sand...', 'SB-Mid-server-4P...', false) called at [lib\/internal\/midtrans-php\/Midtrans\/Transaction.php:23]\n#3 Midtrans\\Transaction::status(NULL) called at [lib\/internal\/midtrans-php\/Midtrans\/Notification.php:26]\n#4 Midtrans\\Notification->__construct('php:\/\/input') called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:116]\n#5 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Midtrans\\Notific...', array('php:\/\/input')) called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:108]\n#6 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Midtrans\\Notific...') called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#7 Magento\\Framework\\ObjectManager\\ObjectManager->get('Midtrans\\Notific...') called at [app\/code\/Midtrans\/Snap\/Controller\/Payment\/Notification.php:56]\n#8 Midtrans\\Snap\\Controller\\Payment\\Notification->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#9 Magento\\Framework\\App\\Action\\Action->dispatch(&Magento\\Framework\\App\\Request\\Http#000000000e8954c5000000005911c361#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#10 Midtrans\\Snap\\Controller\\Payment\\Notification\\Interceptor->___callParent('dispatch', array(&Magento\\Framework\\App\\Request\\Http#000000000e8954c5000000005911c361#)) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#11 Midtrans\\Snap\\Controller\\Payment\\Notification\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#000000000e8954c5000000005911c361#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#12 Midtrans\\Snap\\Controller\\Payment\\Notification\\Interceptor->___callPlugins('dispatch', array(&Magento\\Framework\\App\\Request\\Http#000000000e8954c5000000005911c361#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...'))) called at [generated\/code\/Midtrans\/Snap\/Controller\/Payment\/Notification\/Interceptor.php:26]\n#13 Midtrans\\Snap\\Controller\\Payment\\Notification\\Interceptor->dispatch(&Magento\\Framework\\App\\Request\\Http#000000000e8954c5000000005911c361#) called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#14 Magento\\Framework\\App\\FrontController->processRequest(&Magento\\Framework\\App\\Request\\Http#000000000e8954c5000000005911c361#, &Midtrans\\Snap\\Controller\\Payment\\Notification\\Interceptor#000000000e895535000000005911c361#) called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#15 Magento\\Framework\\App\\FrontController->dispatch(&Magento\\Framework\\App\\Request\\Http#000000000e8954c5000000005911c361#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#16 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', array(&Magento\\Framework\\App\\Request\\Http#000000000e8954c5000000005911c361#)) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#17 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#000000000e8954c5000000005911c361#) called at [vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php:94]\n#18 Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch(&Magento\\Framework\\App\\FrontController\\Interceptor#000000000e895796000000005911c361#, &Closure#000000000e895672000000005911c361#, &Magento\\Framework\\App\\Request\\Http#000000000e8954c5000000005911c361#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#19 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#000000000e8954c5000000005911c361#) called at [vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php:69]\n#20 Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(&Magento\\Framework\\App\\FrontController\\Interceptor#000000000e895796000000005911c361#, &Closure#000000000e895672000000005911c361#, &Magento\\Framework\\App\\Request\\Http#000000000e8954c5000000005911c361#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#21 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#000000000e8954c5000000005911c361#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#22 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', array(&Magento\\Framework\\App\\Request\\Http#000000000e8954c5000000005911c361#), NULL) called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#23 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(&Magento\\Framework\\App\\Request\\Http#000000000e8954c5000000005911c361#) called at [vendor\/magento\/framework\/App\/Http.php:137]\n#24 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#25 Magento\\Framework\\App\\Bootstrap->run(&Magento\\Framework\\App\\Http\\Interceptor#000000000e89543b000000005911c361#) called at [index.php:39]\n<\/pre>","url":"\/snap\/payment\/notification","script_name":"\/index.php"}`

coba hit ulang via postman juga sama,,
bisa tolong dibantu, trims,,

**Comment by Xaxxis** [comment]
Halo @a88y terima kasih atas laporannya. Saat ini plugins terbaru magento 2 berjalan dengan baik pada Magento v2.3.3. Silahkan menggunakan Magento versi terbaru. Pastikan tidak ada redirect pada saat mengirim notifikasi. Terima kasih

**Comment by rizdaprasetya** [comment]
Closed due to inactivity, please reply if you need further follow up
